"""adciona unicidade item-estoque

Revision ID: a4a7e134eede
Revises: 64cc223f576f
Create Date: 2026-09-21 07:41:03.464661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a7e134eede'
down_revision: Union[str, Sequence[str], None] = '64cc223f576f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_column('armazenamento')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armazenamento', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'estoque', ['armazenamento'], ['id'])

    # ### end Alembic commands ###
