"""alterando coluna admin para role

Revision ID: 0fb9fc2336f4
Revises: cbeb052a8bc1
Create Date: 2026-09-26 23:39:27.058550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb9fc2336f4'
down_revision: Union[str, Sequence[str], None] = 'cbeb052a8bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_promocional', sa.Float(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role', sa.String(), nullable=True))
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('Role')

    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_column('preco_promocional')

    # ### end Alembic commands ###
