"""refactor: editando nomenclatura

Revision ID: 28f64a6da98c
Revises: 1d3a29833196
Create Date: 2026-09-23 01:09:18.289332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f64a6da98c'
down_revision: Union[str, Sequence[str], None] = '1d3a29833196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corredores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('coluna', sa.Integer(), nullable=False),
    sa.Column('linha', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_corredores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('corredor_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_corredor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corredor_id'], ['corredores.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'corredor_id', name='uq_item_estoque')
    )
    op.drop_table('estoque')
    op.drop_table('itens_estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_estoque',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('estoque_id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade_corredor', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'estoque_id', name=op.f('uq_item_estoque'))
    )
    op.create_table('estoque',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(), nullable=True),
    sa.Column('coluna', sa.INTEGER(), nullable=False),
    sa.Column('linha', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('itens_corredores')
    op.drop_table('corredores')
    # ### end Alembic commands ###
