"""resolvendo problemas de relationship

Revision ID: a942dc35d20f
Revises: a4a7e134eede
Create Date: 2026-09-21 08:10:54.014757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a942dc35d20f'
down_revision: Union[str, Sequence[str], None] = 'a4a7e134eede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
